### ISSUE TITLE
Does it support total of all record?

### ISSUE THREAD

**Issue by mrhaoji** [douwevandermeij/admin-totals#7]
Firstly, thx for this library!

I have noticed that the TOTAL only Sum the data in current page, does the library support Sum the data of all pages, which means all records in the model or all records after filtering something?

**Comment by douwevandermeij** [comment]
Unfortunately that's not possible since that's deeply rooted in the Django Admin core, where the Querysets are per page and not for the whole set. Changing it could result in unexpected results in different cases. At this moment the results are what you expect, unfortunately not exactly as desired, but that's one of the shortcomings of Django Admin I think (as there are a few more) and keep in mind, Django Admin is not meant as a fully functional back-office application, it's just meant as a simple way to view/alter your data.

Thanks anyway for your feature request!

**Comment by mrhaoji** [comment]
Got u and thx for the reply. And, I figured out an alternate way by increasing list_max_show_all in the ModelAdmin.
